CREATE DATABASE QuanLyCuaHangTienLoi
GO

USE QuanLyCuaHangTienLoi 
GO


CREATE TABLE dbo.NHANVIEN 
(
	TenDangNhap VARCHAR(50) NOT NULL,
	MatKhau VARCHAR(50) NOT NULL,
	TenNguoiDung NVARCHAR(50)  NOT NULL,
	Quyen NVARCHAR(20)  NOT NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(TenDangNhap),

)
GO


CREATE TABLE dbo.KHACHHANG
(
	MaKH VARCHAR(20) NOT NULL,
	TenKH NVARCHAR(50) NOT NULL,
	GioiTinh BIT  NOT NULL,
	DiaChi NVARCHAR(50)  NOT NULL,
	SDT VARCHAR(10)  NOT NULL,
	Email NVARCHAR(50)  NOT NULL,
	CONSTRAINT PK_KHANHHANG PRIMARY KEY(MaKH),
)
GO

CREATE TABLE dbo.DONVITINH (
	MaDVT VARCHAR(10) NOT NULL,
	TenDVT NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_DONVITINH PRIMARY KEY(MaDVT)
)
GO


CREATE TABLE dbo.MATHANG 
(
	MaMH NVARCHAR(50) NOT NULL,
	TenMH NVARCHAR(50)  NOT NULL,
	DonVi VARCHAR(10)  NOT NULL,
	GiaBan INT  NOT NULL,
	SoLuong INT  NOT NULL,
	CONSTRAINT PK_MATHANG PRIMARY KEY(MaMH),
	CONSTRAINT FK_MATHANG_DONVITINH FOREIGN KEY(DonVi) REFERENCES dbo.DONVITINH(MaDVT)
)
GO




CREATE TABLE dbo.HOADON 
(
	MaHD NVARCHAR(50) NOT NULL,
	MaKH VARCHAR(20) NOT NULL,
	NgayTao DATE NOT NULL,
	TenDangNhap VARCHAR(50) NOT NULL,
	TongTien INT NOT NULL,
	CONSTRAINT PK_HOADON PRIMARY KEY(MaHD),
	CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(TenDangNhap) REFERENCES dbo.NHANVIEN(TenDangNhap)
)
GO



CREATE TABLE dbo.NHACUNGCAP 
(
	MaNCC NCHAR(10) NOT NULL,
	TenNCC NVARCHAR(50)  NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	SDT INT NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY(MaNCC)
)
GO




CREATE TABLE dbo.HANGTHANHVIEN
(
	MaHang NCHAR(10) NOT NULL,
	TenHang NVARCHAR(50) NOT NULL,
	QuyenLoi INT  NOT NULL,
	CONSTRAINT PK_HANGTHANHVIEN PRIMARY KEY(MaHang)
)
GO


CREATE TABLE dbo.PHIEUNHAP 
(
	MaPN NCHAR(10) NOT NULL,
	MaNCC NCHAR(10) NOT NULL,
	TenDangNhap VARCHAR(50) NOT NULL,
	NgayNhap DATE NOT NULL,
	CONSTRAINT PK_PHIEUNHAP PRIMARY KEY(MaPN),
	CONSTRAINT FK_PHIEUNHAP_NHACUNGCAP FOREIGN KEY (MaNCC) REFERENCES dbo.NHACUNGCAP(MaNCC)
)
GO




CREATE TABLE dbo.CTHD 
(
	MaHD NVARCHAR(50) NOT NULL,
	MaMH NVARCHAR(50) NOT NULL,
	SoLuong INT  NOT NULL,
	DonGia FLOAT  NOT NULL,
	CONSTRAINT PK_CTHD PRIMARY KEY(MaHD, MaMH),
	CONSTRAINT FK_CTPN_HOADON FOREIGN KEY (MaHD) REFERENCES dbo.HOADON(MaHD),
	CONSTRAINT FK_CTHD_HANGHOA FOREIGN KEY (MaMH) REFERENCES dbo.MATHANG(MaMH)
)
GO



CREATE TABLE dbo.CTPN 
(
	MaPN NCHAR(10) NOT NULL,
	MaMH NVARCHAR(50) NOT NULL,
	SoLuong INT  NOT NULL,
	DonGia FLOAT  NOT NULL,
	CONSTRAINT PK_CTPN PRIMARY KEY(MaPN, MaMH),
	CONSTRAINT FK_CTPN_PHIEUNHAP FOREIGN KEY (MaPN) REFERENCES dbo.PHIEUNHAP(MaPN),
	CONSTRAINT FK_CTPN_HANGHOA FOREIGN KEY (MaMH) REFERENCES dbo.MATHANG(MaMH)
)
GO



